openmapper.fsql.files=src/main/resources/test.fsql,\
  src/main/resources/file1.fsql
openmapper.packagesToScan=com.openmapper.test

#spring.datasource.driverClassName=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/test
#spring.datasource.username=
#spring.datasource.password=
logging.level.com.openmapper=debug